name: Python Linting with Super-Linter

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.2.1
        with:
          # Use the correct syntax for passing custom options
          args: |
            --pylint-config 'pyproject.toml' 
            --severity WARNING 
            --paths 'src/**/*.py' 
            --paths-ignore 'tests/unit/test_*.py' 
